Data Exploration

In [153]:
import pandas as pd
import numpy as np
pd.options.mode.copy_on_write = True

In [154]:
df = pd.read_csv('customer.csv')

In [155]:
df.head()

Unnamed: 0        custid     sex is_employed   income      marital_status  \
0           7  000006646_03    Male        True  22000.0       Never married   
1           8  000007827_01  Female         NaN  23200.0  Divorced/Separated   
2           9  000008359_04  Female        True  21000.0       Never married   
3          10  000008529_01  Female         NaN  37770.0             Widowed   
4          11  000008744_02    Male        True  39000.0  Divorced/Separated   

   health_ins                  housing_type  num_vehicles  age state_of_res  \
0        True      Homeowner free and clear           0.0   24      Alabama   
1        True                        Rented           0.0   82      Alabama   
2        True  Homeowner with mortgage/loan           2.0   31      Alabama   
3        True      Homeowner free and clear           1.0   93      Alabama   
4        True                        Rented           2.0   67      Alabama   

   code_column  gas_usage  rooms recent_move_b  
0         1047      210.0      3             F  
1         1047        3.0      6             T  
2         1047       40.0      3             F  
3         1047      120.0      2             F  
4         1047        3.0      2             F

In [156]:
df.dtypes

Unnamed: 0          int64
custid             object
sex                object
is_employed        object
income            float64
marital_status     object
health_ins           bool
housing_type       object
num_vehicles      float64
age                 int64
state_of_res       object
code_column         int64
gas_usage         float64
rooms               int64
recent_move_b      object
dtype: object

In [157]:
df.isnull().sum()

Unnamed: 0            0
custid                0
sex                   0
is_employed       25515
income                0
marital_status        0
health_ins            0
housing_type       1686
num_vehicles       1686
age                   0
state_of_res          0
code_column           0
gas_usage          1686
rooms                 0
recent_move_b      1687
dtype: int64

In [158]:
df[df["housing_type"].isnull() == True]


Unnamed: 0        custid     sex is_employed   income  \
53             80  000082691_01  Female        True   6400.0   
63            100  000116191_01    Male        True   5000.0   
159           237  000269295_01    Male         NaN      0.0   
204           299  000349708_01    Male         NaN      0.0   
216           311  000362630_01    Male         NaN      0.0   
...           ...           ...     ...         ...      ...   
72290       99764  001464842_01  Female         NaN      0.0   
72354       99859  000325202_01  Female         NaN   9400.0   
72386       99906  000635137_01    Male         NaN  19900.0   
72416       99946  001062738_01    Male         NaN  27000.0   
72457      100000  001520877_01    Male        True  16400.0   

           marital_status  health_ins housing_type  num_vehicles  age  \
53          Never married       False          NaN           NaN   38   
63          Never married        True          NaN           NaN   23   
159         Never married       False          NaN           NaN   47   
204         Never married       False          NaN           NaN   24   
216         Never married        True          NaN           NaN   23   
...                   ...         ...          ...           ...  ...   
72290             Widowed        True          NaN           NaN   90   
72354  Divorced/Separated        True          NaN           NaN   66   
72386       Never married       False          NaN           NaN   27   
72416  Divorced/Separated       False          NaN           NaN   40   
72457       Never married        True          NaN           NaN   31   

      state_of_res  code_column  gas_usage  rooms recent_move_b  
53         Alabama         1047        NaN      3           NaN  
63         Alabama         1047        NaN      3           NaN  
159        Alabama         1047        NaN      3           NaN  
204        Alabama         1047        NaN      4           NaN  
216        Alabama         1047        NaN      6           NaN  
...            ...          ...        ...    ...           ...  
72290    Wisconsin         1305        NaN      5           NaN  
72354      Wyoming          131        NaN      3           NaN  
72386      Wyoming          131        NaN      2           NaN  
72416      Wyoming          131        NaN      3           NaN  
72457      Wyoming          131        NaN      5           NaN  

[1686 rows x 15 columns]

In [159]:

print(1686/72458)
df = df.dropna(subset=["housing_type"])
df[df["housing_type"].isnull() == True]

0.023268652184713905


Empty DataFrame
Columns: [Unnamed: 0, custid, sex, is_employed, income, marital_status, health_ins, housing_type, num_vehicles, age, state_of_res, code_column, gas_usage, rooms, recent_move_b]
Index: []

In [160]:
df[df["housing_type"].isnull() == True]

Empty DataFrame
Columns: [Unnamed: 0, custid, sex, is_employed, income, marital_status, health_ins, housing_type, num_vehicles, age, state_of_res, code_column, gas_usage, rooms, recent_move_b]
Index: []

In [161]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 70772 entries, 0 to 72456
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Unnamed: 0      70772 non-null  int64  
 1   custid          70772 non-null  object 
 2   sex             70772 non-null  object 
 3   is_employed     46668 non-null  object 
 4   income          70772 non-null  float64
 5   marital_status  70772 non-null  object 
 6   health_ins      70772 non-null  bool   
 7   housing_type    70772 non-null  object 
 8   num_vehicles    70772 non-null  float64
 9   age             70772 non-null  int64  
 10  state_of_res    70772 non-null  object 
 11  code_column     70772 non-null  int64  
 12  gas_usage       70772 non-null  float64
 13  rooms           70772 non-null  int64  
 14  recent_move_b   70771 non-null  object 
dtypes: bool(1), float64(3), int64(4), object(7)
memory usage: 8.2+ MB


In [162]:
df[df["recent_move_b"].isnull() == True]

Unnamed: 0        custid     sex is_employed  income marital_status  \
10030       14009  001148287_01  Female       False  5000.0        Married   

       health_ins                  housing_type  num_vehicles  age  \
10030        True  Homeowner with mortgage/loan           0.0   42   

      state_of_res  code_column  gas_usage  rooms recent_move_b  
10030   California         8962        3.0      4           NaN

In [163]:
mode = df["recent_move_b"].mode()[0]
print(mode)
df["recent_move_b"] = df["recent_move_b"].fillna(mode)

F


In [164]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 70772 entries, 0 to 72456
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Unnamed: 0      70772 non-null  int64  
 1   custid          70772 non-null  object 
 2   sex             70772 non-null  object 
 3   is_employed     46668 non-null  object 
 4   income          70772 non-null  float64
 5   marital_status  70772 non-null  object 
 6   health_ins      70772 non-null  bool   
 7   housing_type    70772 non-null  object 
 8   num_vehicles    70772 non-null  float64
 9   age             70772 non-null  int64  
 10  state_of_res    70772 non-null  object 
 11  code_column     70772 non-null  int64  
 12  gas_usage       70772 non-null  float64
 13  rooms           70772 non-null  int64  
 14  recent_move_b   70772 non-null  object 
dtypes: bool(1), float64(3), int64(4), object(7)
memory usage: 8.2+ MB


In [166]:
print(len(pd.unique(df["custid"])))

for col in df.columns:
    print(col)
    print(pd.unique(df[col]))
    print(len(pd.unique(df[col])))
    print("\n")

# por num_vehicles a int
# drop unnamed
# put custid as dataframe index
# gas_usage 1 2 3 to zero and all to int
# Label encoder for categorical variables
# check correlation before dropping code_column


'''
With only 49 unique short integers, it's possible that code_column represents categorical information—like a set of predefined categories, statuses, or codes that could provide insight into the types of health insurance claims, policy categories, or regional designations in the data.

You might try:

    Mapping Values: Print out the unique values to see if they form a pattern (e.g., sequential or grouped by range).

    Frequency Analysis: Count the occurrences of each unique integer to see if they align with other features in the data, such as specific types of insurance plans or claim types.

    Cross-reference: If you have any other resources or metadata about the dataset, these values may correspond to known codes used in health insurance datasets.

If the column remains ambiguous after analysis and appears uncorrelated with other important variables, then it might be safe to drop. However, categorical columns with limited unique values often add context that can be beneficial in health insurance datasets.
'''

70772
Unnamed: 0
[    7     8     9 ... 99997 99998 99999]
70772


custid
['000006646_03' '000007827_01' '000008359_04' ... '001507219_01'
 '001513103_01' '001519624_01']
70772


sex
['Male' 'Female']
2


is_employed
[True nan False]
3


income
[22000. 23200. 21000. ... 25110. 18010. 26850.]
4423


marital_status
['Never married' 'Divorced/Separated' 'Widowed' 'Married']
4


health_ins
[ True False]
2


housing_type
['Homeowner free and clear' 'Rented' 'Homeowner with mortgage/loan'
 'Occupied with no rent']
4


num_vehicles
[0. 2. 1. 5. 3. 4. 6.]
7


age
[ 24  82  31  93  67  76  26  73  27  54  61  64  55  65  33  47  68  46
  58  43  41  62  21  78  32  59  29  70  30  28  86  35  34  40  72  60
  25  79  22  42  44  81  50  45  63  57  39  71  38  49  69  37  66  53
  36  23  75  88  51  85  52  83  77  56  48 100  74  89  80  84   0  87
 120  91 110 114  94  90  96  92  95]
81


state_of_res
['Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California' 'Colorado'
 'Connecticut' 'Delaware'